= Quarkus AdminFaces Showcase
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:numbered:
:doctype: book
:toc: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

This project is based/depends on https://github.com/tandraschko/quarkus-myfaces[quarkus-myfaces^] and https://github.com/rmpestano/quarkus-omnifaces[quarkus-omnifaces^] extensions.

The same https://github.com/adminfaces[AdminFaces showcase^] application running on https://quarkus.io/[Quarkus^].

NOTE: Only hotspot was tested and native mode will probably not work.
 
== How to try it?

=== Build MyFaces 

Following steps will be need while `MyFaces 3.x` is not released:

* `git clone clone https://github.com/apache/myfaces.git`
* `mvn versions:set -DnewVersion=3.0.0-SNAPSHOT -DprocessAllModules`
* `mvn clean install -DskipTests`

=== Build quarkus-myfaces

* `git clone https://github.com/tandraschko/quarkus-myfaces && cd quarkus-myfaces/quarkus-myfaces && mvn clean install`
 
[TIP]
====

To build the quarkus extension you need to add jboss maven repository to your maven settings.xml:

----
<repositories>
    <repository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
    </repository>
</repositories>
<pluginRepositories>
    <pluginRepository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
   </pluginRepository>
</pluginRepositories>
----

====

=== Build quarkus-omnifaces

`git clone https://github.com/rmpestano/quarkus-omnifaces && mvn clean install`

=== Run Admin showcase

Finally run this project: 

* `git clone https://github.com/adminfaces/quarkus-admin-showcase && cd quarkus-admin-showcase && mvn compile quarkus:dev`
* access http://localhost:8080/

TIP: Run via quarkus runner with `mvn clean package && java -jar target/quarkus-admin-showcase-runner.jar`

== Docker

to run via docker execute the following commands:

* `mvn clean package && docker build -f docker/Dockerfile -t rmpestano/quarkus-admin-showcase . && docker run -i --rm -p 8080:8080 rmpestano/quarkus-admin-showcase`

OR run already pushed image:

* `docker run -i --rm -p 8080:8080 rmpestano/quarkus-admin-showcase`

== Demo

The application is deployed on openshift and available here: https://adminfaces.github.io/admin-showcase
